window.onload = function() {
    this.setTimeout(function(){
        const myLiffId = "1654020633-G80mkmam";
        initializeLiffOrDie(myLiffId);
    }, 1000);
};

/**
* Check if myLiffId is null. If null do not initiate liff.
* @param {string} myLiffId The LIFF ID of the selected element
*/
function initializeLiffOrDie(myLiffId) {
    if (!myLiffId) {
        document.getElementById("liffAppContent").classList.add('hidden');
        document.getElementById("liffIdErrorMessage").classList.remove('hidden');
    } else {
        initializeLiff(myLiffId);
    }
}

/**
* Initialize LIFF
* @param {string} myLiffId The LIFF ID of the selected element
*/
function initializeLiff(myLiffId) {
    liff
        .init({
            liffId: myLiffId
        })
        .then(() => {
            // start to use LIFF's api
            initializeApp();
        })
        .catch((err) => {
            console.log(err);
        });
}

/**
 * Initialize the app by calling functions handling individual app components
 */
function initializeApp() {
    displayLiffData();
    displayIsInClientInfo();
    registerButtonHandlers();

}

/**
* Display data generated by invoking LIFF methods
*/
function displayLiffData() {
}

/**
* Toggle the login/logout buttons based on the isInClient status, and display a message accordingly
*/
function displayIsInClientInfo() {
    if (liff.isInClient()) {
        document.getElementById('liffLoginButton').classList.toggle('hidden');
        document.getElementById('liffLogoutButton').classList.toggle('hidden');
    }
}

/**
* Register event handlers for the buttons displayed in the app
*/
function registerButtonHandlers() {
    // 分享好友
    document.getElementById('share').addEventListener('click', function() {
        if (liff.isLoggedIn()) {
            
            liff.getProfile().then(function(profile) {
                liff.shareTargetPicker([
                    temp(profile),
                ])
                    .then(
                    ).catch(function(res) {
                    alert("傳送失敗，請重新嘗試")
                    });
            }).catch(function(error) {
                window.alert('Error getting profile: ' + error);
            });
        } else {
            alert('需要先登入LINE，才可使用愚人節紅包功能');
            liff.login();
        }
    });
}

/**
* Alert the user if LIFF is opened in an external browser and unavailable buttons are tapped
*/
function sendAlertIfNotInClient() {
    alert('This button is unavailable as LIFF is currently being opened in an external browser.');
}

/**
* Toggle access token data field
*/
function toggleAccessToken() {
    toggleElement('accessTokenData');
}

/**
* Toggle profile info field
*/
function toggleProfileData() {
    toggleElement('profileInfo');
}

/**
* Toggle scanCode result field
*/
function toggleQrCodeReader() {
    toggleElement('scanQr');
}

/**
* Toggle specified element
* @param {string} elementId The ID of the selected element
*/
function toggleElement(elementId) {
    const elem = document.getElementById(elementId);
    if (elem.offsetWidth > 0 && elem.offsetHeight > 0) {
        elem.style.display = 'none';
    } else {
        elem.style.display = 'block';
    }
}

function temp(profile) {
    return {
        "type": "flex",
        "altText": "您收到了紅包訊息",
        contents: {
            "type": "bubble",
            "size": "kilo",
            "hero": {
                "type": "image",
                "url": "https://i.imgur.com/uX0T9aB.jpg",
                "size": "full",
                "aspectRatio": "20:13",
                "aspectMode": "cover",
                "action": {
                "type": "uri",
                "uri": "https://funtuan.github.io/april-fools/?openExternalBrowser=1"
                }
            },
            "body": {
                "type": "box",
                "layout": "vertical",
                "contents": [
                {
                    "type": "text",
                    "text": "LIHE Pay 紅包",
                    "weight": "bold",
                    "size": "md"
                },
                {
                    "type": "text",
                    "text": profile.displayName+"發紅包了，限時3天！快來試試手氣！（紅包將在3天後過期並退還給好友。）",
                    "weight": "regular",
                    "size": "sm",
                    "wrap": true,
                    "align": "start",
                    "color": "#555555",
                    "margin": "md"
                }
                ]
            },
            "footer": {
                "type": "box",
                "layout": "vertical",
                "spacing": "sm",
                "contents": [
                {
                    "type": "button",
                    "style": "link",
                    "action": {
                    "type": "uri",
                    "label": "查看紅包狀態",
                    "uri": "https://funtuan.github.io/april-fools/?openExternalBrowser=1"
                    },
                    "height": "sm"
                }
                ],
                "flex": 0
            }
        },
    }
}